import Head from 'next/head'
import { Mint } from "../components/Mint";
import { Navbar } from '../components/Navbar';
import { Embed } from '../components/Embed';
import { Team } from '../components/Team';


export const Home = () => {
  return (
    <>
      <Head>
        <title>NFT Drop Minting dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Embed />
      <Mint />
      <Team />
    </>
  )
}

export default Home



  